fail_fast: true

repos:
- repo: https://github.com/ocular-d/pre-commit-hooks.git
  rev: 0.0.6
  hooks:
    - id: python-black
    - id: python-isort
    - id: vale
    - id: markdown-lint

- repo: local
  hooks:
    - id: hadolint-docker
      name: Lint Dockerfiles
      description: Runs hadolint Docker image to lint Dockerfiles
      language: docker_image
      types: ["dockerfile"]
      entry: hadolint/hadolint:v2.8.0 hadolint

- repo: https://github.com/zricethezav/gitleaks
  rev: v8.2.0
  hooks:
    - id: gitleaks
      name: Gitleaks

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: file-contents-sorter
      name: Sort files (.gitignore, .dockerignore)
      description: Sort .gitignore and .dockerignore alphabetical
      verbose: true
      files: .gitignore|.dockerignore
      args: [--unique]